server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 172.20.10.3:80
    gateway:
      routes:
        - id: payment-Service #路由标识，必须唯一
          uri: lb://paymentService #路由目标地址
          predicates: #路由断言，判断是否符合规则
            - Path=/payment/** #路劲断言，判断路劲是否是以/payment开头，如果是则符合
        - id: order-Service #路由标识，必须唯一
          uri: lb://orderService #路由目标地址
          predicates: #路由断言，判断是否符合规则
            - Path=/consumer/** #路劲断言，判断路劲是否是以/order开头，如果是则符合
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking aowsome!
      globalcors: #全局跨域处理
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求头中携带的头信息
            allow-credentials: true # 是否允许携带cookie
            max-age: 360000 # 检查跨域的有效期
        add-to-simple-url-handler-mapping: true # 解决option请求被拦截问题