server:
  port: 8001
#eureka:
#  client:
#    serviceUrl: #指定服务注册中心的地址
#      defaultZone: http://localhost:8888/eureka/
spring:
#  application:
#    name: paymentService
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: HZ
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.69.201.78/weather_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 286933jl99
#  # 服务模块
#  devtools:
#    restart:
#      enabled: true  # 热部署开关
#      additional-paths: src/main/java #重启目录
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.feign.entity
