server:
  port: 8888 #服务注册中心的端口号
eureka:
  client:
    registerWithEureka: false #是否往服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #指定服务注册中心的地址
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: eurekaServer